# Generated by Django 4.0.6 on 2023-01-28 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('date_joined', models.DateField()),
                ('email', models.EmailField(max_length=256)),
                ('lesson_type', models.CharField(choices=[('B', 'Backend Dev'), ('F', 'Frontend Dev'), ('D', 'Devops'), ('S', 'System Administration'), ('C', 'Cloud Engineering')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('specialization', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=256)),
                ('student', models.ManyToManyField(to='users.student')),
            ],
        ),
    ]
