# Generated by Django 4.0.6 on 2023-01-27 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='schedule',
            field=models.DateTimeField(null=True),
        ),
    ]
