# Generated by Django 4.0.6 on 2023-01-27 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_teacher_schedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='schedule',
        ),
    ]
