# Generated by Django 4.0.6 on 2023-02-14 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_alter_student_lesson_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('date_added', models.DateField()),
                ('student', models.ManyToManyField(to='users.student')),
                ('teacher', models.ManyToManyField(to='users.teacher')),
            ],
        ),
    ]
