# Generated by Django 4.0.6 on 2023-01-27 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_teacher_schedule'),
        ('schedules', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='teacher',
        ),
        migrations.AddField(
            model_name='schedule',
            name='teacher',
            field=models.ManyToManyField(to='users.teacher'),
        ),
    ]
